# permissions for end users to view perconaserverformysqlrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: perconaserverformysqlrestore-viewer-role
rules:
- apiGroups:
  - ps.percona.com
  resources:
  - perconaserverformysqlrestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ps.percona.com
  resources:
  - perconaserverformysqlrestores/status
  verbs:
  - get
