# permissions for end users to edit perconaserverformysqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: perconaserverformysql-editor-role
rules:
- apiGroups:
  - ps.percona.com
  resources:
  - perconaserverformysqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ps.percona.com
  resources:
  - perconaserverformysqls/status
  verbs:
  - get
