# permissions for end users to edit perconaserverformysqlbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: perconaserverformysqlbackup-editor-role
rules:
- apiGroups:
  - ps.percona.com
  resources:
  - perconaserverformysqlbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ps.percona.com
  resources:
  - perconaserverformysqlbackups/status
  verbs:
  - get
