# permissions for end users to edit perconaserverformysqlrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: perconaserverformysqlrestore-editor-role
rules:
- apiGroups:
  - ps.percona.com
  resources:
  - perconaserverformysqlrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ps.percona.com
  resources:
  - perconaserverformysqlrestores/status
  verbs:
  - get
