apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: percona-server-for-mysql-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: percona-server-for-mysql-operator-role
subjects:
- kind: ServiceAccount
  name: percona-server-for-mysql-operator
