apiVersion: ps.percona.com/v2
kind: PerconaServerForMySQL
metadata:
  name: cluster1
spec:
  secretsName: cluster1-secrets
  sslSecretName: cluster1-ssl
  mysql:
    size: 3
    imagePullPolicy: Always
    image: percona/percona-server:8.0.25
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2G
  orchestrator:
    size: 1
    imagePullPolicy: Always
    image: quay.io/presslabs/mysql-operator-orchestrator:0.4.0
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2G
